version: '3.4'

services:
  banking.operation.balance.query.api:
    image: ${DOCKER_REGISTRY-}bankingoperationbalancequeryapi
    build:
      context: .
      dockerfile: Banking.Operation.Balance.Query.Api/Dockerfile
      
networks:
  default:
    external: true
    name: bankingoperation-client-api_backend